---
- hosts: manage
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - file: path=/home/isucon/.ssh state=directory owner=isucon mode=755
    - copy: src=../keys/deploy_id_rsa dest=/home/isucon/.ssh/deploy_id_rsa owner=isucon mode=600
    - git:
        repo=git@github.com:tagomoris/isucon5-final.git
        dest=/home/isucon/isucon5-final
        key_file=/home/isucon/.ssh/deploy_id_rsa
        accept_hostkey=yes
    - name: ruby
      shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
      args:
        chdir: /home/isucon/isucon5-final/eventapp

- hosts: manage
  gather_facts: no
  tasks:
    - copy: src=../files/env.eventapp.sh dest=/home/isucon/env.sh owner=isucon mode=755
    - apt: name=supervisor state=present
    - name: ruby eventapp unicorn
      copy: src=../files/supervisor.eventapp.conf dest=/etc/supervisor/conf.d/eventapp.conf owner=root mode=644
    - supervisorctl: name=eventapp state=present
      ignore_errors: yes
    - supervisorctl: name=eventapp state=restarted
      ignore_errors: yes
